export const mentors = [
    {
        name: "Rohit Dey",
        year: "1st Year, VIT Vellore",
        specialization: "Biotechnology",
        sessions: "11+ sessions (5 reviews)",
        image: "/profiles/profile1.jpg",
        badge: "New mentor",
        rating: null,
        verified: true,
    },
    {
        name: "Akshay kumar",
        year: "3rd Year, NIT Trichy",
        specialization: "Mechanical Engineering",
        sessions: "15+ sessions (8 reviews)",
        image: "/profiles/profile2.jpg",
        badge: null,
        rating: 3.2,
        verified: false,
    },
    {
        name: "Riya Sharma",
        year: "4th Year, AIIMS",
        specialization: "Medicine (MBBS)",
        sessions: "5+ sessions (2 reviews)",
        image: "/profiles/profile3.jpg",
        badge: "New mentor",
        rating: null,
        verified: false,
    },
    {
        name: "Sneha Kapoor",
        year: "1st Year, NID Ahemdabad",
        specialization: "Industrial Design",
        sessions: "100+ sessions (27 reviews)",
        image: "/profiles/profile4.jpg",
        badge: null,
        rating: 4.0,
        verified: true,
    },
    {
        name: "Virat Singh",
        year: "2nd Year, IIT Delhi",
        specialization: "Computer Science",
        sessions: "20+ sessions (10 reviews)",
        image: "/profiles/profile1.jpg",
        badge: "Top mentor",
        rating: 4.5,
        verified: true,
    },
    {
        name: "Priya Gupta",
        year: "3rd Year, Delhi University",
        specialization: "Economics",
        sessions: "8+ sessions (3 reviews)",
        image: "/profiles/profile2.jpg",
        badge: null,
        rating: 3.8,
        verified: true,
    },
    {
        name: "Amit Sharma",
        year: "4th Year, IIM Bangalore",
        specialization: "Business Management",
        sessions: "30+ sessions (15 reviews)",
        image: "/profiles/profile3.jpg",
        badge: null,
        rating: 4.7,
        verified: true,
    },
    {
        name: "Deepika Padukone",
        year: "1st Year, NIFT Delhi",
        specialization: "Fashion Design",
        sessions: "12+ sessions (6 reviews)",
        image: "/profiles/profile4.jpg",
        badge: "New mentor",
        rating: null,
        verified: false,
    },
    {
        name: "Suresh Raina",
        year: "2nd Year, SRM University",
        specialization: "Civil Engineering",
        sessions: "7+ sessions (2 reviews)",
        image: "/profiles/profile1.jpg",
        badge: null,
        rating: 3.0,
        verified: false,
    },
    {
        name: "Anushka Sharma",
        year: "3rd Year, JNU",
        specialization: "Political Science",
        sessions: "18+ sessions (9 reviews)",
        image: "/profiles/profile2.jpg",
        badge: null,
        rating: 4.2,
        verified: true,
    },
    {
        name: "Rahul Dravid",
        year: "4th Year, Oxford University",
        specialization: "History",
        sessions: "25+ sessions (12 reviews)",
        image: "/profiles/profile3.jpg",
        badge: "Top mentor",
        rating: 4.9,
        verified: true,
    },
    {
        name: "Kareena Kapoor",
        year: "1st Year, Symbiosis Pune",
        specialization: "Mass Communication",
        sessions: "6+ sessions (1 review)",
        image: "/profiles/profile4.jpg",
        badge: "New mentor",
        rating: null,
        verified: false,
    },
    {
        name: "Shah Rukh Khan",
        year: "2nd Year, Jamia Millia Islamia",
        specialization: "Journalism",
        sessions: "14+ sessions (7 reviews)",
        image: "/profiles/profile1.jpg",
        badge: null,
        rating: 4.0,
        verified: true,
    },
    {
        name: "Alia Bhatt",
        year: "3rd Year, Ashoka University",
        specialization: "Psychology",
        sessions: "9+ sessions (4 reviews)",
        image: "/profiles/profile2.jpg",
        badge: null,
        rating: 3.5,
        verified: true,
    },
    {
        name: "MS Dhoni",
        year: "4th Year, Anna University",
        specialization: "Electrical Engineering",
        sessions: "22+ sessions (11 reviews)",
        image: "/profiles/profile3.jpg",
        badge: null,
        rating: 4.6,
        verified: true,
    },
    {
        name: "Priyanka Chopra",
        year: "1st Year, Amity University",
        specialization: "Law",
        sessions: "10+ sessions (5 reviews)",
        image: "/profiles/profile4.jpg",
        badge: "New mentor",
        rating: null,
        verified: false,
    },
    {
        name: "Ranbir Kapoor",
        year: "2nd Year, St. Xavier's College",
        specialization: "Sociology",
        sessions: "16+ sessions (8 reviews)",
        image: "/profiles/profile1.jpg",
        badge: null,
        rating: 4.1,
        verified: true,
    },
    {
        name: "Katrina Kaif",
        year: "3rd Year, Christ University",
        specialization: "Commerce",
        sessions: "13+ sessions (6 reviews)",
        image: "/profiles/profile2.jpg",
        badge: null,
        rating: 3.9,
        verified: true,
    },
    {
        name: "Hrithik Roshan",
        year: "4th Year, IIT Bombay",
        specialization: "Aerospace Engineering",
        sessions: "28+ sessions (14 reviews)",
        image: "/profiles/profile3.jpg",
        badge: null,
        rating: 4.8,
        verified: true,
    },
    {
        name: "Sara Ali Khan",
        year: "1st Year, Lady Shri Ram College",
        specialization: "English Literature",
        sessions: "4+ sessions (1 review)",
        image: "/profiles/profile4.jpg",
        badge: "New mentor",
        rating: null,
        verified: false,
    },
];

export const universities = [
    { value: "VIT Vellore", label: "VIT Vellore" },
    { value: "IIT Delhi", label: "IIT Delhi" },
    { value: "aiims", label: "AIIMS" },
    { value: "nit", label: "NIT" },
    { value: "nid", label: "NID" },
];

export const yearsOfStudy = [
    { value: "1", label: "1st Year" },
    { value: "2", label: "2nd Year" },
    { value: "3", label: "3rd Year" },
    { value: "4", label: "4th Year" },
];

export const specializations = [
    { value: "Biotechnology", label: "Biotechnology" },
    { value: "Mechanical Engineering", label: "Mechanical Engineering" },
    { value: "Civil Engineering", label: "Civil Engineering" },
    { value: "design", label: "Industrial Design" },
];

export const competitiveExams = [
    { value: "jee", label: "JEE" },
    { value: "neet", label: "NEET" },
    { value: "cat", label: "CAT" },
];

export const courses = [
    { value: "ug", label: "Undergraduate" },
    { value: "pg", label: "Postgraduate" },
    { value: "phd", label: "Doctor of Philosophy"}
]; 

export const pastSessions = [
    {
        name: "Akash Pandey",
        year: "1st year",
        institution: "IIT Bombay",
        department: "Software Engineering",
        date: "Wed, Aug 28",
        time: "5:30 PM - 6:00 PM",
    },
    {
        name: "Akash Pandey",
        year: "1st year",
        institution: "IIT Bombay",
        department: "Software Engineering",
        date: "Wed, Aug 28",
        time: "5:30 PM - 6:00 PM",
    },
    {
        name: "Akash Pandey",
        year: "1st year",
        institution: "IIT Bombay",
        department: "Software Engineering",
        date: "Wed, Aug 28",
        time: "5:30 PM - 6:00 PM",
    },
];

export const upcomingSessions = [
    {
        name: "Sheetal Kapoor",
        year: "2nd year",
        institution: "NIFT Delhi",
        department: "Fashion Communication Department",
        date: "Mon, Sept 02",
        time: "5:30 PM - 6:00 PM",
    },
    {
        name: "Sheetal Kapoor",
        year: "2nd year",
        institution: "NIFT Delhi",
        department: "Fashion Communication Department",
        date: "Mon, Sept 02",
        time: "5:30 PM - 6:00 PM",
    },
];
